import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"
import tsParser from "@typescript-eslint/parser"
import unicorn from "eslint-plugin-unicorn"

import localRules from "./eslint-local-rules/index.js"

export default [
  {
    ignores: [".next/**", "node_modules/**", "public/**", "cypress/**", "*.config.*", "eslint-local-rules/**"],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "local-rules": { rules: localRules },
      unicorn,
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { args: "all", argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "unicorn/catch-error-name": "warn",
      "max-len": ["warn", { code: 130, ignoreUrls: true }],
      "import/newline-after-import": ["warn", { count: 1 }],
      "local-rules/no-export-const-classname": "warn",
      "local-rules/no-localstorage-direct": "warn",
      "local-rules/no-banned-words": "error",
      "local-rules/no-function-in-deps": "warn",
      "local-rules/no-vague-names": "warn",
      "local-rules/style-before-classname": "warn",
      "local-rules/sdk-method-naming": "warn",
      "local-rules/no-throwaway-alias": "warn",
      "local-rules/no-zustand-types-in-store-file": "warn",
      "local-rules/input-value-naming": "warn",
      "local-rules/handle-prefix-location": "warn",
      "local-rules/no-process-env-non-null-assertion": "warn",
      "local-rules/arrow-fn-only-for-hooks": "warn",
      "local-rules/ts-ignore-dynamic-table-only": "warn",
      "local-rules/type-naming-prefix": "warn",
      "local-rules/no-type-export-in-action-or-component": "warn",
      "local-rules/imports-order": "warn",
      "local-rules/no-cross-route-group-absolute-import": "warn",
      "local-rules/require-absolute-import-for-shared-folders": "warn",
      "local-rules/function-body-own-line": "warn",
      "local-rules/console-log-line-number": "warn",
      "local-rules/no-redundant-return-parens": "warn",
      "local-rules/no-zustand-selector": "warn",
      "local-rules/zustand-state-setter-pairing": "warn",
      "local-rules/prefer-inline-zustand-setter": "warn",
      "local-rules/api-type-req-resp-suffix": "warn",
      "local-rules/no-req-json-catch": "warn",
      "local-rules/no-void-only-jsx-handler": "warn",
      "local-rules/no-handlers-variable": "warn",
      "local-rules/no-inner-component": "warn",
      "local-rules/arrow-parens-avoid": "warn",
      "local-rules/hook-naming-convention": "warn",
      "local-rules/db-redis-verb-naming": "warn",
    },
  },
  {
    // Supabase's own generated file (regenerated by `pnpm update-types`) - renaming its exported
    // types to match our T-prefix convention wouldn't survive the next regen.
    files: ["app/interfaces/types_db.ts"],
    rules: {
      "local-rules/type-naming-prefix": "off",
    },
  },
]
