name: Cypress E2E Tests

on:
  push:
    branches:
      - development # Adjust branch as needed
  pull_request:
    types: [opened, synchronize]

jobs:
  run-cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    environment: NEXT_PRODUCTION_URL
    env:
      NEXT_PRODUCTION_URL: "29-ai-companion.vercel.app"
      NEXT_DEVELOPMENT_URL: "http://localhost:3029"
      NEXT_PUBLIC_SUPABASE_URL: "https://vahemcbozzowgcadavfm.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaGVtY2Jvenpvd2djYWRhdmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDY5Nzc4MDIsImV4cCI6MjAyMjU1MzgwMn0.NbhCKZEig0m6arLOR7RvljTOmO0pPiPLKmkjzn89AFE"
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "dndlcofnb"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      # To make CI faster
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm
          key: node-modules-deps${{hashFiles('**/pnpm-lock.yaml')}}

      - name: Print env
        run: |
          echo "development url $NEXT_DEVELOPMENT_URL"
          echo "supabase url $NEXT_PUBLIC_SUPABASE_URL"
          echo "anon key $NEXT_PUBLIC_SUPABASE_ANON_KEY"
          echo "service role key $SUPABASE_SERVICE_ROLE_KEY"
          echo "cloudinary name $NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm dev
        env:
          NEXT_PRODUCTION_URL: ${{ env.NEXT_PRODUCTION_URL }}
          NEXT_DEVELOPMENT_URL: ${{ env.NEXT_DEVELOPMENT_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
