name: Cypress E2E Tests

on:
  push:
    branches:
      - development # Adjust branch as needed
  pull_request:
    types: [opened, synchronize]

jobs:
  run-cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm dev
        env:
          NEXT_PRODUCTION_URL: "29-ai-companion.vercel.app"
          NEXT_DEVELOPMENT_URL: "http://localhost:3029"
          NEXT_PUBLIC_SUPABASE_URL: "https://vahemcbozzowgcadavfm.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "random-anon-key"
          SUPABASE_SERVICE_ROLE_KEY: "random-service-role-key"
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
