name: Cypress E2E Tests

on:
  push:
    branches:
      - development # Adjust branch as needed
  pull_request:
    types: [opened, synchronize]

jobs:
  run-cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Start Next.js app
        run: bun dev

      - name: Run Cypress tests
        run: bun cypress:run
