name: Cypress E2E Tests

on:
  push:
    branches:
      - development # Adjust branch as needed
  pull_request:
    types: [opened, synchronize]

jobs:
  run-cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: bun i

      - name: Start Next.js app
        run: bun dev -p 3029 &

      - name: Wait for app to start
        run: npx wait-on http://localhost:3029
        timeout-minutes: 5

      - name: Run Cypress tests
        run: bun cypress:run
